(define (problem typed-bomberman-rows4-cols2)
(:domain gold-miner-typed)
(:objects 
        loc_0 loc_1 
        loc_2 loc_3 
        loc_4 loc_5 
        loc_6 loc_7  - LOC
)
(:init
(arm-empty)
(connected loc_0 loc_1)
(connected loc_2 loc_3)
(connected loc_4 loc_5)
(connected loc_6 loc_7)
(connected loc_0 loc_2)
(connected loc_1 loc_3)
(connected loc_2 loc_4)
(connected loc_3 loc_5)
(connected loc_4 loc_6)
(connected loc_5 loc_7)
(connected loc_1 loc_0)
(connected loc_3 loc_2)
(connected loc_5 loc_4)
(connected loc_7 loc_6)
(connected loc_2 loc_0)
(connected loc_3 loc_1)
(connected loc_4 loc_2)
(connected loc_5 loc_3)
(connected loc_6 loc_4)
(connected loc_7 loc_5)
(robot-at loc_0)
(clear loc_0)
(gold-at loc_1)
(soft-rock-at loc_1)
(clear loc_2)
(soft-rock-at loc_3)
(bomb-at loc_4)
(laser-at loc_4)
(clear loc_4)
(hard-rock-at loc_5)
(clear loc_6)
(soft-rock-at loc_7)
)
(:goal
(holds-gold)
)
)
