(define (problem grid-3-5-2-3-2)
    (:domain grid)
    (:objects
    object_0 object_1 object_2 object_3 object_4 object_5 object_6 object_7 object_8 object_9 object_10 object_11 object_12 object_13 object_14
    object_15 object_16
    object_17 object_18 object_19
    )

    (:init
       (arm-empty)

       (place object_0)
       (place object_1)
       (place object_2)
       (place object_3)
       (place object_4)
       (place object_5)
       (place object_6)
       (place object_7)
       (place object_8)
       (place object_9)
       (place object_10)
       (place object_11)
       (place object_12)
       (place object_13)
       (place object_14)
       (shape object_15)
       (shape object_16)
       (key object_17)
       (key object_18)
       (key object_19)

       (conn object_0 object_5)
       (conn object_0 object_1)
       (conn object_1 object_6)
       (conn object_1 object_2)
       (conn object_1 object_0)
       (conn object_2 object_7)
       (conn object_2 object_3)
       (conn object_2 object_1)
       (conn object_3 object_8)
       (conn object_3 object_4)
       (conn object_3 object_2)
       (conn object_4 object_9)
       (conn object_4 object_3)
       (conn object_5 object_10)
       (conn object_5 object_6)
       (conn object_5 object_0)
       (conn object_6 object_11)
       (conn object_6 object_7)
       (conn object_6 object_1)
       (conn object_6 object_5)
       (conn object_7 object_12)
       (conn object_7 object_8)
       (conn object_7 object_2)
       (conn object_7 object_6)
       (conn object_8 object_13)
       (conn object_8 object_9)
       (conn object_8 object_3)
       (conn object_8 object_7)
       (conn object_9 object_14)
       (conn object_9 object_4)
       (conn object_9 object_8)
       (conn object_10 object_11)
       (conn object_10 object_5)
       (conn object_11 object_12)
       (conn object_11 object_6)
       (conn object_11 object_10)
       (conn object_12 object_13)
       (conn object_12 object_7)
       (conn object_12 object_11)
       (conn object_13 object_14)
       (conn object_13 object_8)
       (conn object_13 object_12)
       (conn object_14 object_9)
       (conn object_14 object_13)
       (locked object_4)
       (locked object_14)
       (lock-shape  object_4 object_15)
       (lock-shape  object_14 object_16)
       (open object_0)
       (open object_1)
       (open object_2)
       (open object_3)
       (open object_5)
       (open object_6)
       (open object_7)
       (open object_8)
       (open object_9)
       (open object_10)
       (open object_11)
       (open object_12)
       (open object_13)

       (key-shape  object_17 object_15)
       (key-shape  object_18 object_16)
       (key-shape  object_19 object_15)
       (at object_17 object_3)
       (at object_18 object_10)
       (at object_19 object_7)
       (at-robot object_10)
    )

    (:goal (and
       (at object_17 object_2)
    )))
    
